/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zms_signup;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.io.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.renderer.category.BarRenderer;

/**
 *
 * @author Srikanth
 */
public class animalchart extends javax.swing.JFrame {

    /**
     * Creates new form animalchart
     */
    public animalchart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("create chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
          {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/zms","root","5123");
                System.out.println("Database Connection Successful");
                Statement stmt = (Statement) conn.createStatement();
                String query="select (select count(animal_type) from animal where animal_type='mammal') as mammals,(select count(animal_type) from animal where animal_type='reptile')as reptiles, (select count(animal_type) from animal where animal_type='Amphibian')as amphibians, (select count(animal_type) from animal where animal_type='bird')as birds from dual;";
                //JDBCCategoryDataset dataset1=new JDBCCategoryDataset(conn,query);  
                ResultSet rs=stmt.executeQuery(query);
                rs.next();
                int mamcount=Integer.parseInt(rs.getString("mammals"));
                int repcount=Integer.parseInt(rs.getString("reptiles"));
                int amphicount=Integer.parseInt(rs.getString("amphibians"));
                int birdcount=Integer.parseInt(rs.getString("birds"));
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                dataset.addValue(mamcount,"animals","mammals");
                dataset.addValue(repcount,"animals","reptiles");
                dataset.addValue(amphicount,"animals","amphibians");
                dataset.addValue(birdcount,"animals","birds");
                
                JFreeChart barchart=ChartFactory.createBarChart("animals ","animal type","count",dataset,PlotOrientation.VERTICAL,true,true,false);
                
                
                BarRenderer renderer=null;
                renderer = new BarRenderer();
                ChartFrame frame=new ChartFrame("animals",barchart);
                frame.setVisible(true);
                frame.setSize(500,500);
                        
                
             //   int width =500;
               // int height=500;
               // File BarChart=new File("bar2.jpeg");
                //ChartUtilities.saveChartAsJPEG(BarChart,barchart,width,height);
                           
                
             
                
            }
                catch (Exception e)
                {
                e.printStackTrace();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(animalchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(animalchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(animalchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(animalchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new animalchart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
